---

- name: "configuration play." 
  hosts: web
  user: ubuntu
  gather_facts: false
  vars:
    - ansible_python_interpreter: /usr/bin/python3
    - ansible_host_key_checking: false
    - ansible_stdout_callback: yaml
  environment:
      TYPEORM_CONNECTION: "{{ lookup('env','TYPEORM_CONNECTION') }}"
      TYPEORM_PORT: "{{ lookup('env','TYPEORM_PORT') }}"
      TYPEORM_HOST: "{{ lookup('env','TYPEORM_HOST') }}"
      TYPEORM_USERNAME: "{{ lookup('env','TYPEORM_USERNAME') }}"
      TYPEORM_PASSWORD: "{{ lookup('env','TYPEORM_PASSWORD') }}"
      TYPEORM_DATABASE: "{{ lookup('env','TYPEORM_DATABASE') }}"
      TYPEORM_MIGRATIONS: "{{ lookup('env','TYPEORM_MIGRATIONS') }}"
      TYPEORM_ENTITIES: "{{ lookup('env','TYPEORM_ENTITIES') }}"

- name: check environments
  shell: echo $TYPEORM_CONNECTION

- name: Basic usage
  debug:
    msg: "'{{ lookup('env', 'TYPEORM_CONNECTION') }}' is the TYPEORM_CONNECTION environment variable."
- name: Basic usage
  debug:
    msg: "'{{ lookup('env', 'TYPEORM_PORT') }}' is the TYPEORM_PORT environment variable."
- name: Basic usage
  debug:
    msg: "'{{ lookup('env', 'TYPEORM_HOST') }}' is the TYPEORM_HOST environment variable. "

  roles:
    - deploy

